package com.polaris.yiyao.activity.dao;


import com.polaris.yiyao.activity.dto.ActivityInfoDTO;

public interface ActivityInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insert(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insertSelective(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    ActivityInfoDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityInfoDTO activityInfoDTO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityInfoDTO activityInfoDTO);
}